name: Bug Report
description: Report a bug to the developer.
title: "[Bug] <title>"
labels: [New, Bug]
body:
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what the issue is.
    placeholder: Eg. Monitors will not turn off like they used to.
  validations:
    required: true
- type: textarea
  attributes:
    label: Mod Build
    description: List what versions this issue is happening on.
    placeholder: Eg. 4.4.1, 4.5.0...
  validations:
    required: true
- type: textarea
  attributes:
    label: Minecraft Release
    description: List what minecraft versions this issue is happening on.
    placeholder: Eg. 1.18.2, 1.19.2...
  validations:
    required: true
- type: textarea
  attributes:
    label: Crash Report
    description: Provide a crash file from your game or server.
    placeholder: Only rquired if there was a crash.
  validations:
    required: false
